snapshot.go
This fix adds two new useful bindings for the snapshot interface:
Enables reverting to a snapshot by providing a wrapper to
virDomainRevertToSnapshot.
Enable deleting a snapshot (which is not covered by simply calling the
existing virDomainSnapshotFree wrapper) by providing a wrapper to
virDomainSnapshotDelete.
=> Enable Reverting to Snapshots

storage_volume.go, storage_volume_test.go
According to http://fossies.org/linux/libvirt/src/libvirt_public.syms it is around since 0.4.1.
=> add virStoragePoolLookupByVolume

cfuncs.go, events.go, libvirt.go
Issue #64 : Golang 1.6 doesn't support C pointers to go memory, so they don't build anyway.
A hacky-solution might be some multi-threaded approach to support domain events,
but let's make the rest of the bindings work without domain events for now
until a permanent solution comes later.
=> Don't build Domain Event callbacks in Golang 1.6

README.md, constants.go, domain.go, domain_test.go, libvirt_test.go
@rgbkrk Review, please. 
This commit exposes the libvirt wrapper around QEMU Monitor Command support,
which proxies monitor commands through libvirt, including a supporting
test in domain_test.go.
The test uses a QEMU-based libvirt domain which has no state, so it should
compile fine (I hope) on anybody's system.
Comments welcome. =)
=> QEMU Monitor Command support

cfuncs.go, events.go, events_test.go
So this might seem crazy to a C developer, but it could be the right way to do this.
Once you're past the hacks converting ints to pointers, it's probably the simplest way to this.
Basically, instead of passing pointers to C, we pass a integer id. Then we maintain a global map from integer ids to context objects.
Using a global mutex to locking access for the map, this pattern is safe.
The callback passed to C is just a static go function, which then finds the context object in the global map.
A C developer might question the sanity of using a hash map for resolving ids, when the ids are effectively pointers. But this seems like the simplest way to get static reference to an object in go.
I also suspect that most of these events are fairly low frequency, so efficiency probably isn't …
=> Adding events support for go 1.6

domain.go, domain_test.go
The test is using buildTestQEMUDomain() because the test driver does
not support other create flags besides VIR_DOMAIN_NONE.
domain.CreateWithFlags(VIR_DOMAIN_NONE) is the same as domain.Create()
=> Add CreateWithFlags() for domain

libvirt.go
Since ptr is not exported, we need a function to allow it to be set
by another package.
Also, since the type of ptr is derived from C, other packages cannot
be cast to that type (C.virConnectPtr becomes libvirt.C.virConnectPtr)
- at least they could not as far as I could tell.
This function will solve both problems by being exported, and then
handling the type casting to C.virConnectPtr. This way someone can
just send us a pointer to the connection they created themselves,
and we can still use it in the library.
---
The reason I want to do this is because the [virConnectOpenAuth](https://libvirt.org/html/libvirt-libvirt-host.html#virConnectOpenAuth) function is not implemented in this package. I wanted to just implement that method here, but did not figure out how to handle types declared …
=> Add method to enable setting ptr on VirConnection

cfuncs.go, events.go
On x86-64, GoInt is 64bit, therefore using int for goCallbackId
introduces a truncation. It is therefore safer to use a type that is as
large as expected. We cannot use something larger as on 32bit arch, long
long is bigger than void*. From a C perspective, this is something safe
as sizeof(long) == sizeof(void *) on almost [all archs][0].
The cast to void* is modified to be symmetric and safe. The unmodified
long is stored inside the pointer and is retrieved unmodified.
cc @jonasfj @hinesmr @rgbkrk as this relates to #69.
[0]: https://wiki.debian.org/ArchitectureSpecificsMemo#Summary
=> Promote goCallbackId to a C long

cfuncs.go, events.go
ba5e0139775a brought event support for Go 1.6. Some comments were left
and may lead people to believe that events are not supported. Remove
them.
=> Remove outdated comments about Golang 1.6 and events

domain_test.go
When spawning a new domain without specifying any network interface, we
don't expect to have any interface configured. The test was expecting
2.
Also gofmt the corresponding test file.
=> Fix QEMU test with domain interfaces

cfuncs.go
Recent versions of gcc will complain about all the callbacks defined in
Go and called from C are undefined functions.
We cannot use the generated "_cgo_export.h" file because it is not
present yet. Introducing intermediary C functions that will call the Go
function from a separate .c file importing "_cgo_export.h" seems
overkill. Manual declaration of function prototypes is bothersome (and
would need to be checked). Use of C preprocessor may help a bit but
won't help in correctness as only the content of "_cgo_export.h"
matters.
Therefore, it just seems easier to ignore those warnings.
=> Remove "implicit declaration of function" warning

events.go, events_test.go
The callback ID to return is the one from C, to be used to deregister
the event. The test is modified to check the error. The initial
goCallbackId value is also modified to exhibit the error. This can be
dropped from this commit if it seems too odd.
=> Return the C callbackId for virConnectDomainEventRegisterAny

domain.go
Each use of `C.CString()` allocates a new buffer that should be released
after use. This was the only place this wasn't done.
=> domain: fix missing C.free()

cfuncs.go, error.go, error_test.go, events.go, events_test.go, libvirt.go
Hey!
This PR enables one to setup error callbacks. The second commit implements `virSetErrorFunc()` function which sets the global error callback. This is the most useful one. We keep the default to silent stderr.
The first commit is taken from #94 and is needed for the last one. The last commit implements `virConnSetErrorFunc()`. However, since without it, errors are passed to the global handlers, it is not that useful. We could discard the first and last commit of this PR if this seems too invasive. Note however that by default, there is no handler and therefore the last commit will only impact users of this feature. So, it should be safe.
Moreover, I will need the first commit for another PR (close callbacks).
=> Error callbacks

libvirt.go, libvirt_test.go
The test needs a real QEMU connection as this feature is not supported
by the test driver. Also, the documentation mentions the return code is
-1 for generic errors and 1 if the remote end doesn't support
keepalives. However, a quick test shows that the test backend will just
return -1. virsh is just testing if the return code is different of
0. Therefore, it seems safer to trigger an error if return code != 0.
=> Add SetKeepAlive() function to enable keepalive probes

events.go
When registering/deregistering a lot of callbacks, in a long-running
process, it may be possible for `nextGoCallbackId` to
overflow. Therefore, after incrementing it, check that its number is not
already used. This should be a rare event as the map should stay quite
sparse.
=> events: handle overflow of callback IDs

domain_1.2.14_test.go, domain_test.go, error_test.go, events_test.go, integration_test.go, interface_test.go, libvirt_test.go, network_test.go, storage_pool_test.go, storage_volume_test.go
If ConnectionClose() method doesn't return 0, this means we have either
an error, either there is still a reference to the connection by another
object (we don't have virConnectRef()). In all tests, check that return
code and ensure this is 0. Fix tests that weren't releasing all objects
correctly.
=> test: ensure we don't have any connection leak

libvirt.go
Those two changes break the API backward compatibility! I do this PR to see how others feel about those functions.
The first function was introduced in #81 to workaround the absence of
virConnectOpenAuth() method. This defeats the purpose of having an
opaque structure for a connection. Now that there is a mechanism to
handle callbacks, it should be easier to implement virConnectOpenAuth()
correctly.
The second function should not exist as there is no way to increment
reference of an existing connection from Go code (virConnectRef() is not
implemented). Therefore, if this function was needed, this should be
because the C code increments a reference to a connection but the
appropriate call to decrement it is absent. For example, we requested a
domain but we didn't free it. Therefore, the …
=> connection: remove dangerous SetPtr() and UnrefAndCloseConnection() methods

error.go, error_test.go, libvirt.go
When calling `GetLastError()` twice in a row, we get a segfault because
`virGetLastError()` C function returns nil. We cannot return nil since
we don't return a pointer, but we can return a special error that means
"no error".
=> errors: don't make GetLastError() segfault when on no error condition

libvirt.go
This is done automatically and if the connection has been closed
unexpectedly, this will trigger an error. We ignore the error but it can
appear in the logs.
=> connection: do not unregister close callback on close

libvirt_test.go
The case for the driver name has changed in libvirt 2.3.0. Be more
generic.
=> Make GetType test pass with libvirt 2.3.0

README.md, vagrant/Vagrantfile
Minor cleanup for `Vagrantfile`:
- move `/libvirt-go` to `/opt/go/src/libvirt` (which is a part of `$GOPATH`) so that external binaries will be able to import it
- remove the branch name from the path to `Vagrantfile`, since only one branch is checked out at any single time, and it should probably include just one `Vagrantfile`, the correct one for the current branch
=> Vagrant cleanup

events.go, events_test.go
A golang lib should use idiomatic return values of error and nil instead
of int as is common in C. This updates these functions to return as
expected.
=> events: Return values should use golang idioms

domain.go
This makes it consistent with the GetNrVirtCpu method which returns
uint16. Quoting the libvirt upstream: "65536 cpus ought to be enough for
everybody"
This fixes GH issue #117
=> domain: Change vcpus uint setter to uint16
